# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c30b3b878794749fb7377fde61cbe7ddc4085245f8b1befe9ea4509121cb37fa9a52a7db97b9a08c849df9ff2e82de1fecc49a0db2627a99c615e2b76564b2

test:
  secret_key_base: 69b92184c4af17355031290033771a30ca5dd9f7a24830fb014eb34a9140e7b332e37191ff199e1d7a1992b4b13b66b798ed31956bfc677b1415b15dcc2aad9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
